################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/kits/common/bsp/bsp_bcc.c \
D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/kits/common/bsp/bsp_stk.c \
D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/kits/common/bsp/bsp_stk_leds.c \
D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/kits/common/bsp/bsp_trace.c \
D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/kits/common/drivers/dmactrl.c \
D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_assert.c \
D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_cmu.c \
D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_emu.c \
D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_gpio.c \
D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_int.c \
D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_ldma.c \
D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_leuart.c \
D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_rmu.c \
D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_rtc.c \
D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_rtcc.c \
D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_system.c \
D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_timer.c \
D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_usart.c \
D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emdrv/gpiointerrupt/src/gpiointerrupt.c \
D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/hal/hal_common.c \
D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/hal/efr32/hal_efr.c \
D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/kits/common/drivers/retargetio.c \
D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/kits/common/drivers/retargetserial.c \
D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emdrv/rtcdrv/src/rtcdriver.c \
D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/kits/common/drivers/udelay.c \
D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emdrv/ustimer/src/ustimer.c 

OBJS += \
./hal-efr32/bsp_bcc.o \
./hal-efr32/bsp_stk.o \
./hal-efr32/bsp_stk_leds.o \
./hal-efr32/bsp_trace.o \
./hal-efr32/dmactrl.o \
./hal-efr32/em_assert.o \
./hal-efr32/em_cmu.o \
./hal-efr32/em_emu.o \
./hal-efr32/em_gpio.o \
./hal-efr32/em_int.o \
./hal-efr32/em_ldma.o \
./hal-efr32/em_leuart.o \
./hal-efr32/em_rmu.o \
./hal-efr32/em_rtc.o \
./hal-efr32/em_rtcc.o \
./hal-efr32/em_system.o \
./hal-efr32/em_timer.o \
./hal-efr32/em_usart.o \
./hal-efr32/gpiointerrupt.o \
./hal-efr32/hal_common.o \
./hal-efr32/hal_efr.o \
./hal-efr32/retargetio.o \
./hal-efr32/retargetserial.o \
./hal-efr32/rtcdriver.o \
./hal-efr32/udelay.o \
./hal-efr32/ustimer.o 

C_DEPS += \
./hal-efr32/bsp_bcc.d \
./hal-efr32/bsp_stk.d \
./hal-efr32/bsp_stk_leds.d \
./hal-efr32/bsp_trace.d \
./hal-efr32/dmactrl.d \
./hal-efr32/em_assert.d \
./hal-efr32/em_cmu.d \
./hal-efr32/em_emu.d \
./hal-efr32/em_gpio.d \
./hal-efr32/em_int.d \
./hal-efr32/em_ldma.d \
./hal-efr32/em_leuart.d \
./hal-efr32/em_rmu.d \
./hal-efr32/em_rtc.d \
./hal-efr32/em_rtcc.d \
./hal-efr32/em_system.d \
./hal-efr32/em_timer.d \
./hal-efr32/em_usart.d \
./hal-efr32/gpiointerrupt.d \
./hal-efr32/hal_common.d \
./hal-efr32/hal_efr.d \
./hal-efr32/retargetio.d \
./hal-efr32/retargetserial.d \
./hal-efr32/rtcdriver.d \
./hal-efr32/udelay.d \
./hal-efr32/ustimer.d 


# Each subdirectory must supply rules for building sources it contributes
hal-efr32/bsp_bcc.o: D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/kits/common/bsp/bsp_bcc.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -IC:/Users/Szarlej/SimplicityStudio/v3_workspace/Test -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/graphics" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32MG1_BRD4151A/config" -I"C:\Users\Szarlej\SimplicityStudio\v3_workspace\Test\lcd-graphics_inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32MG1P/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --dlib_config "D:\Soft\IAR Systems\Embedded Workbench 7.3\arm\inc\c\DLib_Config_Normal.h" --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DEFR32MG1P232F256GM48=1' '-DBOARD_BRD4151A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' --diag_suppress Pa050 --dependencies=m "$(basename $(notdir $<)).d"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/bsp_stk.o: D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/kits/common/bsp/bsp_stk.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -IC:/Users/Szarlej/SimplicityStudio/v3_workspace/Test -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/graphics" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32MG1_BRD4151A/config" -I"C:\Users\Szarlej\SimplicityStudio\v3_workspace\Test\lcd-graphics_inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32MG1P/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --dlib_config "D:\Soft\IAR Systems\Embedded Workbench 7.3\arm\inc\c\DLib_Config_Normal.h" --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DEFR32MG1P232F256GM48=1' '-DBOARD_BRD4151A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' --diag_suppress Pa050 --dependencies=m "$(basename $(notdir $<)).d"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/bsp_stk_leds.o: D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/kits/common/bsp/bsp_stk_leds.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -IC:/Users/Szarlej/SimplicityStudio/v3_workspace/Test -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/graphics" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32MG1_BRD4151A/config" -I"C:\Users\Szarlej\SimplicityStudio\v3_workspace\Test\lcd-graphics_inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32MG1P/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --dlib_config "D:\Soft\IAR Systems\Embedded Workbench 7.3\arm\inc\c\DLib_Config_Normal.h" --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DEFR32MG1P232F256GM48=1' '-DBOARD_BRD4151A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' --diag_suppress Pa050 --dependencies=m "$(basename $(notdir $<)).d"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/bsp_trace.o: D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/kits/common/bsp/bsp_trace.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -IC:/Users/Szarlej/SimplicityStudio/v3_workspace/Test -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/graphics" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32MG1_BRD4151A/config" -I"C:\Users\Szarlej\SimplicityStudio\v3_workspace\Test\lcd-graphics_inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32MG1P/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --dlib_config "D:\Soft\IAR Systems\Embedded Workbench 7.3\arm\inc\c\DLib_Config_Normal.h" --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DEFR32MG1P232F256GM48=1' '-DBOARD_BRD4151A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' --diag_suppress Pa050 --dependencies=m "$(basename $(notdir $<)).d"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/dmactrl.o: D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/kits/common/drivers/dmactrl.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -IC:/Users/Szarlej/SimplicityStudio/v3_workspace/Test -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/graphics" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32MG1_BRD4151A/config" -I"C:\Users\Szarlej\SimplicityStudio\v3_workspace\Test\lcd-graphics_inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32MG1P/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --dlib_config "D:\Soft\IAR Systems\Embedded Workbench 7.3\arm\inc\c\DLib_Config_Normal.h" --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DEFR32MG1P232F256GM48=1' '-DBOARD_BRD4151A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' --diag_suppress Pa050 --dependencies=m "$(basename $(notdir $<)).d"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/em_assert.o: D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_assert.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -IC:/Users/Szarlej/SimplicityStudio/v3_workspace/Test -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/graphics" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32MG1_BRD4151A/config" -I"C:\Users\Szarlej\SimplicityStudio\v3_workspace\Test\lcd-graphics_inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32MG1P/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --dlib_config "D:\Soft\IAR Systems\Embedded Workbench 7.3\arm\inc\c\DLib_Config_Normal.h" --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DEFR32MG1P232F256GM48=1' '-DBOARD_BRD4151A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' --diag_suppress Pa050 --dependencies=m "$(basename $(notdir $<)).d"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/em_cmu.o: D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_cmu.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -IC:/Users/Szarlej/SimplicityStudio/v3_workspace/Test -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/graphics" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32MG1_BRD4151A/config" -I"C:\Users\Szarlej\SimplicityStudio\v3_workspace\Test\lcd-graphics_inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32MG1P/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --dlib_config "D:\Soft\IAR Systems\Embedded Workbench 7.3\arm\inc\c\DLib_Config_Normal.h" --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DEFR32MG1P232F256GM48=1' '-DBOARD_BRD4151A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' --diag_suppress Pa050 --dependencies=m "$(basename $(notdir $<)).d"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/em_emu.o: D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_emu.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -IC:/Users/Szarlej/SimplicityStudio/v3_workspace/Test -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/graphics" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32MG1_BRD4151A/config" -I"C:\Users\Szarlej\SimplicityStudio\v3_workspace\Test\lcd-graphics_inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32MG1P/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --dlib_config "D:\Soft\IAR Systems\Embedded Workbench 7.3\arm\inc\c\DLib_Config_Normal.h" --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DEFR32MG1P232F256GM48=1' '-DBOARD_BRD4151A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' --diag_suppress Pa050 --dependencies=m "$(basename $(notdir $<)).d"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/em_gpio.o: D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_gpio.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -IC:/Users/Szarlej/SimplicityStudio/v3_workspace/Test -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/graphics" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32MG1_BRD4151A/config" -I"C:\Users\Szarlej\SimplicityStudio\v3_workspace\Test\lcd-graphics_inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32MG1P/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --dlib_config "D:\Soft\IAR Systems\Embedded Workbench 7.3\arm\inc\c\DLib_Config_Normal.h" --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DEFR32MG1P232F256GM48=1' '-DBOARD_BRD4151A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' --diag_suppress Pa050 --dependencies=m "$(basename $(notdir $<)).d"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/em_int.o: D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_int.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -IC:/Users/Szarlej/SimplicityStudio/v3_workspace/Test -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/graphics" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32MG1_BRD4151A/config" -I"C:\Users\Szarlej\SimplicityStudio\v3_workspace\Test\lcd-graphics_inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32MG1P/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --dlib_config "D:\Soft\IAR Systems\Embedded Workbench 7.3\arm\inc\c\DLib_Config_Normal.h" --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DEFR32MG1P232F256GM48=1' '-DBOARD_BRD4151A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' --diag_suppress Pa050 --dependencies=m "$(basename $(notdir $<)).d"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/em_ldma.o: D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_ldma.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -IC:/Users/Szarlej/SimplicityStudio/v3_workspace/Test -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/graphics" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32MG1_BRD4151A/config" -I"C:\Users\Szarlej\SimplicityStudio\v3_workspace\Test\lcd-graphics_inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32MG1P/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --dlib_config "D:\Soft\IAR Systems\Embedded Workbench 7.3\arm\inc\c\DLib_Config_Normal.h" --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DEFR32MG1P232F256GM48=1' '-DBOARD_BRD4151A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' --diag_suppress Pa050 --dependencies=m "$(basename $(notdir $<)).d"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/em_leuart.o: D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_leuart.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -IC:/Users/Szarlej/SimplicityStudio/v3_workspace/Test -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/graphics" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32MG1_BRD4151A/config" -I"C:\Users\Szarlej\SimplicityStudio\v3_workspace\Test\lcd-graphics_inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32MG1P/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --dlib_config "D:\Soft\IAR Systems\Embedded Workbench 7.3\arm\inc\c\DLib_Config_Normal.h" --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DEFR32MG1P232F256GM48=1' '-DBOARD_BRD4151A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' --diag_suppress Pa050 --dependencies=m "$(basename $(notdir $<)).d"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/em_rmu.o: D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_rmu.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -IC:/Users/Szarlej/SimplicityStudio/v3_workspace/Test -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/graphics" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32MG1_BRD4151A/config" -I"C:\Users\Szarlej\SimplicityStudio\v3_workspace\Test\lcd-graphics_inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32MG1P/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --dlib_config "D:\Soft\IAR Systems\Embedded Workbench 7.3\arm\inc\c\DLib_Config_Normal.h" --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DEFR32MG1P232F256GM48=1' '-DBOARD_BRD4151A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' --diag_suppress Pa050 --dependencies=m "$(basename $(notdir $<)).d"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/em_rtc.o: D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_rtc.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -IC:/Users/Szarlej/SimplicityStudio/v3_workspace/Test -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/graphics" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32MG1_BRD4151A/config" -I"C:\Users\Szarlej\SimplicityStudio\v3_workspace\Test\lcd-graphics_inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32MG1P/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --dlib_config "D:\Soft\IAR Systems\Embedded Workbench 7.3\arm\inc\c\DLib_Config_Normal.h" --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DEFR32MG1P232F256GM48=1' '-DBOARD_BRD4151A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' --diag_suppress Pa050 --dependencies=m "$(basename $(notdir $<)).d"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/em_rtcc.o: D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_rtcc.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -IC:/Users/Szarlej/SimplicityStudio/v3_workspace/Test -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/graphics" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32MG1_BRD4151A/config" -I"C:\Users\Szarlej\SimplicityStudio\v3_workspace\Test\lcd-graphics_inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32MG1P/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --dlib_config "D:\Soft\IAR Systems\Embedded Workbench 7.3\arm\inc\c\DLib_Config_Normal.h" --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DEFR32MG1P232F256GM48=1' '-DBOARD_BRD4151A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' --diag_suppress Pa050 --dependencies=m "$(basename $(notdir $<)).d"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/em_system.o: D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_system.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -IC:/Users/Szarlej/SimplicityStudio/v3_workspace/Test -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/graphics" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32MG1_BRD4151A/config" -I"C:\Users\Szarlej\SimplicityStudio\v3_workspace\Test\lcd-graphics_inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32MG1P/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --dlib_config "D:\Soft\IAR Systems\Embedded Workbench 7.3\arm\inc\c\DLib_Config_Normal.h" --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DEFR32MG1P232F256GM48=1' '-DBOARD_BRD4151A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' --diag_suppress Pa050 --dependencies=m "$(basename $(notdir $<)).d"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/em_timer.o: D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_timer.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -IC:/Users/Szarlej/SimplicityStudio/v3_workspace/Test -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/graphics" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32MG1_BRD4151A/config" -I"C:\Users\Szarlej\SimplicityStudio\v3_workspace\Test\lcd-graphics_inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32MG1P/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --dlib_config "D:\Soft\IAR Systems\Embedded Workbench 7.3\arm\inc\c\DLib_Config_Normal.h" --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DEFR32MG1P232F256GM48=1' '-DBOARD_BRD4151A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' --diag_suppress Pa050 --dependencies=m "$(basename $(notdir $<)).d"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/em_usart.o: D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emlib/src/em_usart.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -IC:/Users/Szarlej/SimplicityStudio/v3_workspace/Test -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/graphics" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32MG1_BRD4151A/config" -I"C:\Users\Szarlej\SimplicityStudio\v3_workspace\Test\lcd-graphics_inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32MG1P/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --dlib_config "D:\Soft\IAR Systems\Embedded Workbench 7.3\arm\inc\c\DLib_Config_Normal.h" --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DEFR32MG1P232F256GM48=1' '-DBOARD_BRD4151A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' --diag_suppress Pa050 --dependencies=m "$(basename $(notdir $<)).d"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/gpiointerrupt.o: D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emdrv/gpiointerrupt/src/gpiointerrupt.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -IC:/Users/Szarlej/SimplicityStudio/v3_workspace/Test -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/graphics" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32MG1_BRD4151A/config" -I"C:\Users\Szarlej\SimplicityStudio\v3_workspace\Test\lcd-graphics_inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32MG1P/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --dlib_config "D:\Soft\IAR Systems\Embedded Workbench 7.3\arm\inc\c\DLib_Config_Normal.h" --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DEFR32MG1P232F256GM48=1' '-DBOARD_BRD4151A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' --diag_suppress Pa050 --dependencies=m "$(basename $(notdir $<)).d"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/hal_common.o: D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/hal/hal_common.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -IC:/Users/Szarlej/SimplicityStudio/v3_workspace/Test -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/graphics" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32MG1_BRD4151A/config" -I"C:\Users\Szarlej\SimplicityStudio\v3_workspace\Test\lcd-graphics_inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32MG1P/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --dlib_config "D:\Soft\IAR Systems\Embedded Workbench 7.3\arm\inc\c\DLib_Config_Normal.h" --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DEFR32MG1P232F256GM48=1' '-DBOARD_BRD4151A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' --diag_suppress Pa050 --dependencies=m "$(basename $(notdir $<)).d"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/hal_efr.o: D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/hal/efr32/hal_efr.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -IC:/Users/Szarlej/SimplicityStudio/v3_workspace/Test -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/graphics" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32MG1_BRD4151A/config" -I"C:\Users\Szarlej\SimplicityStudio\v3_workspace\Test\lcd-graphics_inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32MG1P/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --dlib_config "D:\Soft\IAR Systems\Embedded Workbench 7.3\arm\inc\c\DLib_Config_Normal.h" --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DEFR32MG1P232F256GM48=1' '-DBOARD_BRD4151A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' --diag_suppress Pa050 --dependencies=m "$(basename $(notdir $<)).d"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/retargetio.o: D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/kits/common/drivers/retargetio.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -IC:/Users/Szarlej/SimplicityStudio/v3_workspace/Test -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/graphics" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32MG1_BRD4151A/config" -I"C:\Users\Szarlej\SimplicityStudio\v3_workspace\Test\lcd-graphics_inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32MG1P/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --dlib_config "D:\Soft\IAR Systems\Embedded Workbench 7.3\arm\inc\c\DLib_Config_Normal.h" --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DEFR32MG1P232F256GM48=1' '-DBOARD_BRD4151A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' --diag_suppress Pa050 --dependencies=m "$(basename $(notdir $<)).d"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/retargetserial.o: D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/kits/common/drivers/retargetserial.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -IC:/Users/Szarlej/SimplicityStudio/v3_workspace/Test -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/graphics" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32MG1_BRD4151A/config" -I"C:\Users\Szarlej\SimplicityStudio\v3_workspace\Test\lcd-graphics_inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32MG1P/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --dlib_config "D:\Soft\IAR Systems\Embedded Workbench 7.3\arm\inc\c\DLib_Config_Normal.h" --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DEFR32MG1P232F256GM48=1' '-DBOARD_BRD4151A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' --diag_suppress Pa050 --dependencies=m "$(basename $(notdir $<)).d"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/rtcdriver.o: D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emdrv/rtcdrv/src/rtcdriver.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -IC:/Users/Szarlej/SimplicityStudio/v3_workspace/Test -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/graphics" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32MG1_BRD4151A/config" -I"C:\Users\Szarlej\SimplicityStudio\v3_workspace\Test\lcd-graphics_inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32MG1P/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --dlib_config "D:\Soft\IAR Systems\Embedded Workbench 7.3\arm\inc\c\DLib_Config_Normal.h" --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DEFR32MG1P232F256GM48=1' '-DBOARD_BRD4151A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' --diag_suppress Pa050 --dependencies=m "$(basename $(notdir $<)).d"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/udelay.o: D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/kits/common/drivers/udelay.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -IC:/Users/Szarlej/SimplicityStudio/v3_workspace/Test -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/graphics" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32MG1_BRD4151A/config" -I"C:\Users\Szarlej\SimplicityStudio\v3_workspace\Test\lcd-graphics_inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32MG1P/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --dlib_config "D:\Soft\IAR Systems\Embedded Workbench 7.3\arm\inc\c\DLib_Config_Normal.h" --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DEFR32MG1P232F256GM48=1' '-DBOARD_BRD4151A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' --diag_suppress Pa050 --dependencies=m "$(basename $(notdir $<)).d"
	@echo 'Finished building: $<'
	@echo ' '

hal-efr32/ustimer.o: D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/emdrv/ustimer/src/ustimer.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -IC:/Users/Szarlej/SimplicityStudio/v3_workspace/Test -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/graphics" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32MG1_BRD4151A/config" -I"C:\Users\Szarlej\SimplicityStudio\v3_workspace\Test\lcd-graphics_inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32MG1P/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --dlib_config "D:\Soft\IAR Systems\Embedded Workbench 7.3\arm\inc\c\DLib_Config_Normal.h" --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DEFR32MG1P232F256GM48=1' '-DBOARD_BRD4151A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' --diag_suppress Pa050 --dependencies=m "$(basename $(notdir $<)).d"
	@echo 'Finished building: $<'
	@echo ' '


