################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/reptile/glib/glib/bmp.c \
D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/kits/common/drivers/display.c \
D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/kits/common/drivers/displayls013b7dh03.c \
D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/kits/common/drivers/displaypalemlib.c \
D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/reptile/glib/dmd/display/dmd_display.c \
D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/reptile/glib/glib/glib.c \
D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/reptile/glib/glib/glib_bitmap.c \
D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/reptile/glib/glib/glib_circle.c \
D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/reptile/glib/glib/glib_font_narrow_6x8.c \
D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/reptile/glib/glib/glib_font_normal_8x8.c \
D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/reptile/glib/glib/glib_font_number_16x20.c \
D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/reptile/glib/glib/glib_line.c \
D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/reptile/glib/glib/glib_polygon.c \
D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/reptile/glib/glib/glib_rectangle.c \
D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/reptile/glib/glib/glib_string.c \
../lcd-graphics/graphics.c 

OBJS += \
./lcd-graphics/bmp.o \
./lcd-graphics/display.o \
./lcd-graphics/displayls013b7dh03.o \
./lcd-graphics/displaypalemlib.o \
./lcd-graphics/dmd_display.o \
./lcd-graphics/glib.o \
./lcd-graphics/glib_bitmap.o \
./lcd-graphics/glib_circle.o \
./lcd-graphics/glib_font_narrow_6x8.o \
./lcd-graphics/glib_font_normal_8x8.o \
./lcd-graphics/glib_font_number_16x20.o \
./lcd-graphics/glib_line.o \
./lcd-graphics/glib_polygon.o \
./lcd-graphics/glib_rectangle.o \
./lcd-graphics/glib_string.o \
./lcd-graphics/graphics.o 

C_DEPS += \
./lcd-graphics/bmp.d \
./lcd-graphics/display.d \
./lcd-graphics/displayls013b7dh03.d \
./lcd-graphics/displaypalemlib.d \
./lcd-graphics/dmd_display.d \
./lcd-graphics/glib.d \
./lcd-graphics/glib_bitmap.d \
./lcd-graphics/glib_circle.d \
./lcd-graphics/glib_font_narrow_6x8.d \
./lcd-graphics/glib_font_normal_8x8.d \
./lcd-graphics/glib_font_number_16x20.d \
./lcd-graphics/glib_line.d \
./lcd-graphics/glib_polygon.d \
./lcd-graphics/glib_rectangle.d \
./lcd-graphics/glib_string.d \
./lcd-graphics/graphics.d 


# Each subdirectory must supply rules for building sources it contributes
lcd-graphics/bmp.o: D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/reptile/glib/glib/bmp.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -IC:/Users/Szarlej/SimplicityStudio/v3_workspace/Test -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/graphics" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32MG1_BRD4151A/config" -I"C:\Users\Szarlej\SimplicityStudio\v3_workspace\Test\lcd-graphics_inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32MG1P/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --dlib_config "D:\Soft\IAR Systems\Embedded Workbench 7.3\arm\inc\c\DLib_Config_Normal.h" --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DEFR32MG1P232F256GM48=1' '-DBOARD_BRD4151A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' --diag_suppress Pa050 --dependencies=m "$(basename $(notdir $<)).d"
	@echo 'Finished building: $<'
	@echo ' '

lcd-graphics/display.o: D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/kits/common/drivers/display.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -IC:/Users/Szarlej/SimplicityStudio/v3_workspace/Test -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/graphics" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32MG1_BRD4151A/config" -I"C:\Users\Szarlej\SimplicityStudio\v3_workspace\Test\lcd-graphics_inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32MG1P/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --dlib_config "D:\Soft\IAR Systems\Embedded Workbench 7.3\arm\inc\c\DLib_Config_Normal.h" --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DEFR32MG1P232F256GM48=1' '-DBOARD_BRD4151A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' --diag_suppress Pa050 --dependencies=m "$(basename $(notdir $<)).d"
	@echo 'Finished building: $<'
	@echo ' '

lcd-graphics/displayls013b7dh03.o: D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/kits/common/drivers/displayls013b7dh03.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -IC:/Users/Szarlej/SimplicityStudio/v3_workspace/Test -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/graphics" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32MG1_BRD4151A/config" -I"C:\Users\Szarlej\SimplicityStudio\v3_workspace\Test\lcd-graphics_inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32MG1P/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --dlib_config "D:\Soft\IAR Systems\Embedded Workbench 7.3\arm\inc\c\DLib_Config_Normal.h" --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DEFR32MG1P232F256GM48=1' '-DBOARD_BRD4151A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' --diag_suppress Pa050 --dependencies=m "$(basename $(notdir $<)).d"
	@echo 'Finished building: $<'
	@echo ' '

lcd-graphics/displaypalemlib.o: D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/kits/common/drivers/displaypalemlib.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -IC:/Users/Szarlej/SimplicityStudio/v3_workspace/Test -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/graphics" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32MG1_BRD4151A/config" -I"C:\Users\Szarlej\SimplicityStudio\v3_workspace\Test\lcd-graphics_inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32MG1P/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --dlib_config "D:\Soft\IAR Systems\Embedded Workbench 7.3\arm\inc\c\DLib_Config_Normal.h" --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DEFR32MG1P232F256GM48=1' '-DBOARD_BRD4151A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' --diag_suppress Pa050 --dependencies=m "$(basename $(notdir $<)).d"
	@echo 'Finished building: $<'
	@echo ' '

lcd-graphics/dmd_display.o: D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/reptile/glib/dmd/display/dmd_display.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -IC:/Users/Szarlej/SimplicityStudio/v3_workspace/Test -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/graphics" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32MG1_BRD4151A/config" -I"C:\Users\Szarlej\SimplicityStudio\v3_workspace\Test\lcd-graphics_inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32MG1P/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --dlib_config "D:\Soft\IAR Systems\Embedded Workbench 7.3\arm\inc\c\DLib_Config_Normal.h" --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DEFR32MG1P232F256GM48=1' '-DBOARD_BRD4151A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' --diag_suppress Pa050 --dependencies=m "$(basename $(notdir $<)).d"
	@echo 'Finished building: $<'
	@echo ' '

lcd-graphics/glib.o: D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/reptile/glib/glib/glib.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -IC:/Users/Szarlej/SimplicityStudio/v3_workspace/Test -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/graphics" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32MG1_BRD4151A/config" -I"C:\Users\Szarlej\SimplicityStudio\v3_workspace\Test\lcd-graphics_inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32MG1P/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --dlib_config "D:\Soft\IAR Systems\Embedded Workbench 7.3\arm\inc\c\DLib_Config_Normal.h" --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DEFR32MG1P232F256GM48=1' '-DBOARD_BRD4151A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' --diag_suppress Pa050 --dependencies=m "$(basename $(notdir $<)).d"
	@echo 'Finished building: $<'
	@echo ' '

lcd-graphics/glib_bitmap.o: D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/reptile/glib/glib/glib_bitmap.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -IC:/Users/Szarlej/SimplicityStudio/v3_workspace/Test -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/graphics" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32MG1_BRD4151A/config" -I"C:\Users\Szarlej\SimplicityStudio\v3_workspace\Test\lcd-graphics_inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32MG1P/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --dlib_config "D:\Soft\IAR Systems\Embedded Workbench 7.3\arm\inc\c\DLib_Config_Normal.h" --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DEFR32MG1P232F256GM48=1' '-DBOARD_BRD4151A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' --diag_suppress Pa050 --dependencies=m "$(basename $(notdir $<)).d"
	@echo 'Finished building: $<'
	@echo ' '

lcd-graphics/glib_circle.o: D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/reptile/glib/glib/glib_circle.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -IC:/Users/Szarlej/SimplicityStudio/v3_workspace/Test -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/graphics" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32MG1_BRD4151A/config" -I"C:\Users\Szarlej\SimplicityStudio\v3_workspace\Test\lcd-graphics_inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32MG1P/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --dlib_config "D:\Soft\IAR Systems\Embedded Workbench 7.3\arm\inc\c\DLib_Config_Normal.h" --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DEFR32MG1P232F256GM48=1' '-DBOARD_BRD4151A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' --diag_suppress Pa050 --dependencies=m "$(basename $(notdir $<)).d"
	@echo 'Finished building: $<'
	@echo ' '

lcd-graphics/glib_font_narrow_6x8.o: D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/reptile/glib/glib/glib_font_narrow_6x8.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -IC:/Users/Szarlej/SimplicityStudio/v3_workspace/Test -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/graphics" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32MG1_BRD4151A/config" -I"C:\Users\Szarlej\SimplicityStudio\v3_workspace\Test\lcd-graphics_inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32MG1P/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --dlib_config "D:\Soft\IAR Systems\Embedded Workbench 7.3\arm\inc\c\DLib_Config_Normal.h" --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DEFR32MG1P232F256GM48=1' '-DBOARD_BRD4151A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' --diag_suppress Pa050 --dependencies=m "$(basename $(notdir $<)).d"
	@echo 'Finished building: $<'
	@echo ' '

lcd-graphics/glib_font_normal_8x8.o: D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/reptile/glib/glib/glib_font_normal_8x8.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -IC:/Users/Szarlej/SimplicityStudio/v3_workspace/Test -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/graphics" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32MG1_BRD4151A/config" -I"C:\Users\Szarlej\SimplicityStudio\v3_workspace\Test\lcd-graphics_inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32MG1P/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --dlib_config "D:\Soft\IAR Systems\Embedded Workbench 7.3\arm\inc\c\DLib_Config_Normal.h" --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DEFR32MG1P232F256GM48=1' '-DBOARD_BRD4151A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' --diag_suppress Pa050 --dependencies=m "$(basename $(notdir $<)).d"
	@echo 'Finished building: $<'
	@echo ' '

lcd-graphics/glib_font_number_16x20.o: D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/reptile/glib/glib/glib_font_number_16x20.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -IC:/Users/Szarlej/SimplicityStudio/v3_workspace/Test -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/graphics" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32MG1_BRD4151A/config" -I"C:\Users\Szarlej\SimplicityStudio\v3_workspace\Test\lcd-graphics_inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32MG1P/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --dlib_config "D:\Soft\IAR Systems\Embedded Workbench 7.3\arm\inc\c\DLib_Config_Normal.h" --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DEFR32MG1P232F256GM48=1' '-DBOARD_BRD4151A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' --diag_suppress Pa050 --dependencies=m "$(basename $(notdir $<)).d"
	@echo 'Finished building: $<'
	@echo ' '

lcd-graphics/glib_line.o: D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/reptile/glib/glib/glib_line.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -IC:/Users/Szarlej/SimplicityStudio/v3_workspace/Test -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/graphics" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32MG1_BRD4151A/config" -I"C:\Users\Szarlej\SimplicityStudio\v3_workspace\Test\lcd-graphics_inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32MG1P/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --dlib_config "D:\Soft\IAR Systems\Embedded Workbench 7.3\arm\inc\c\DLib_Config_Normal.h" --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DEFR32MG1P232F256GM48=1' '-DBOARD_BRD4151A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' --diag_suppress Pa050 --dependencies=m "$(basename $(notdir $<)).d"
	@echo 'Finished building: $<'
	@echo ' '

lcd-graphics/glib_polygon.o: D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/reptile/glib/glib/glib_polygon.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -IC:/Users/Szarlej/SimplicityStudio/v3_workspace/Test -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/graphics" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32MG1_BRD4151A/config" -I"C:\Users\Szarlej\SimplicityStudio\v3_workspace\Test\lcd-graphics_inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32MG1P/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --dlib_config "D:\Soft\IAR Systems\Embedded Workbench 7.3\arm\inc\c\DLib_Config_Normal.h" --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DEFR32MG1P232F256GM48=1' '-DBOARD_BRD4151A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' --diag_suppress Pa050 --dependencies=m "$(basename $(notdir $<)).d"
	@echo 'Finished building: $<'
	@echo ' '

lcd-graphics/glib_rectangle.o: D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/reptile/glib/glib/glib_rectangle.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -IC:/Users/Szarlej/SimplicityStudio/v3_workspace/Test -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/graphics" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32MG1_BRD4151A/config" -I"C:\Users\Szarlej\SimplicityStudio\v3_workspace\Test\lcd-graphics_inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32MG1P/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --dlib_config "D:\Soft\IAR Systems\Embedded Workbench 7.3\arm\inc\c\DLib_Config_Normal.h" --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DEFR32MG1P232F256GM48=1' '-DBOARD_BRD4151A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' --diag_suppress Pa050 --dependencies=m "$(basename $(notdir $<)).d"
	@echo 'Finished building: $<'
	@echo ' '

lcd-graphics/glib_string.o: D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA/submodules/reptile/glib/glib/glib_string.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -IC:/Users/Szarlej/SimplicityStudio/v3_workspace/Test -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/graphics" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32MG1_BRD4151A/config" -I"C:\Users\Szarlej\SimplicityStudio\v3_workspace\Test\lcd-graphics_inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32MG1P/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --dlib_config "D:\Soft\IAR Systems\Embedded Workbench 7.3\arm\inc\c\DLib_Config_Normal.h" --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DEFR32MG1P232F256GM48=1' '-DBOARD_BRD4151A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' --diag_suppress Pa050 --dependencies=m "$(basename $(notdir $<)).d"
	@echo 'Finished building: $<'
	@echo ' '

lcd-graphics/graphics.o: ../lcd-graphics/graphics.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_wrap_diagnostics -IC:/Users/Szarlej/SimplicityStudio/v3_workspace/Test -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/rtcdrv/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/ustimer/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/gpiointerrupt/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emdrv/common/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/emlib/inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/bsp" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/common/drivers" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//hal/efr32" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/common" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/graphics" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/glib" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/reptile/glib/dmd" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/memory_manager" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/response_print" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//utils/command_interpreter" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32/rf/common/cortex" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/kits/EFR32MG1_BRD4151A/config" -I"C:\Users\Szarlej\SimplicityStudio\v3_workspace\Test\lcd-graphics_inc" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/CMSIS/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/Device/SiliconLabs/EFR32MG1P/Include" -I"D:/Projects/Gecko/SiliconLabs/SiliconLabsRAIL/1.2.0.0-GA//submodules/rail_lib/chip/efr32" -e --cpu Cortex-M4F --fpu VFPv4_sp --debug --dlib_config "D:\Soft\IAR Systems\Embedded Workbench 7.3\arm\inc\c\DLib_Config_Normal.h" --endian little --cpu_mode thumb -On --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling '-DEFR32MG1P232F256GM48=1' '-DBOARD_BRD4151A=1' '-DCONFIGURATION_HEADER="rail-configuration.h"' '-DRETARGET_VCOM=1' --diag_suppress Pa050 --dependencies=m "$(basename $(notdir $<)).d"
	@echo 'Finished building: $<'
	@echo ' '


